apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.svc_type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  selector:
{{ toYaml .Values.labels | indent 4 }}
